In [8]:
import numpy as np
import matplotlib.pyplot as plt
import math
import sympy as sp
import scipy.interpolate

In [2]:
t=sp.symbols('t')
y=sp.symbols('y')
#f_2a=sp.exp(t-y)
f_2a=y+sp.cos(math.pi*t)
f_2a

y + cos(3.14159265358979*t)

We want to find h, base on N = 10, O<=t<=2

In [3]:
N=10

In [4]:
h=(2-0)/10
h

0.2

In [5]:
t=np.linspace(0,2,int(N)+1)
t

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

# Euler method

In [6]:
def f_2a(t,y):
    f=y+sp.cos(math.pi*t)
    return f

In [7]:
W = np.zeros(len(t))
W[0] = 2
for n in range(0,len(t)-1 ):
         W[n+1] = W[n] + f_2a(W[n],t[n])*(t[n+1] - t[n])
W

array([2.        , 2.2       , 2.4018034 , 2.54252816, 2.63588636,
       2.71307623, 2.78897332, 2.87133851, 2.9674552 , 3.08849965,
       3.25618004])

In [8]:
t

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [9]:
y_exact=((2*math.pi**2+3)*np.exp(t)+math.pi*np.sin(math.pi*t)-np.cos(math.pi*t))/(math.pi**2+1)
y_exact

array([ 2.        ,  2.65062979,  3.36734688,  4.11518096,  4.9001451 ,
        5.77864435,  6.85022788,  8.23702688, 10.05843316, 12.41154628,
       15.36590324])

the error compare between Euler method and exact solution

In [10]:
[abs(W[i]-y_exact[i]) for i in np.arange(N+1)]

[0.0,
 0.4506297858079473,
 0.9655434810731283,
 1.5726527943619986,
 2.264258738666989,
 3.0655681207647216,
 4.061254565342606,
 5.365688367289149,
 7.09097795595891,
 9.32304663166306,
 12.109723201254821]

# Modified Euler method

In [11]:
h=0.2
N=10
W=np.zeros(N+1)
W[0]=2
t=np.linspace(0,2,int(N)+1)
for i in np.arange(1,int(N)+1):
    W[i]=W[i-1]+(h/2)*( f_2a(t[i-1],W[i-1]) + f_2a(t[i],W[i-1] +h*f_2a(t[i-1],W[i-1]) ) )
W

array([ 2.        ,  2.6409017 ,  3.34988381,  4.09303859,  4.87552334,
        5.75105644,  6.81538715,  8.18678859,  9.98170174, 12.29565986,
       15.19778707])

In [12]:
t

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [13]:
y_exact=((2*math.pi**2+3)*np.exp(t)+math.pi*np.sin(math.pi*t)-np.cos(math.pi*t))/(math.pi**2+1)
y_exact

array([ 2.        ,  2.65062979,  3.36734688,  4.11518096,  4.9001451 ,
        5.77864435,  6.85022788,  8.23702688, 10.05843316, 12.41154628,
       15.36590324])

the error compare between Modified Euler method and exact solution


In [14]:
[abs(W[i]-y_exact[i]) for i in np.arange(N+1)]

[0.0,
 0.009728086370452527,
 0.017463067871885674,
 0.022142364731358555,
 0.02462175367116881,
 0.027587914305224004,
 0.03484072592170584,
 0.050238288744481,
 0.07673142032391667,
 0.11588641695556667,
 0.1681161701999052]

# Midpoint method

In [15]:
h=0.2
N=10
W=np.zeros(N+1)
W[0]=2
t=np.linspace(0,2,int(N)+1)
for i in np.arange(1,int(N)+1):
    W[i]=W[i-1]+h*f_2a( t[i-1] + h/2, W[i-1] + (h/2)*f_2a( t[i-1],W[i-1] ) )
W

array([ 2.        ,  2.6502113 ,  3.36699518,  4.11391446,  4.89523825,
        5.76579902,  6.8240635 ,  8.19162009,  9.98759616, 12.30860471,
       15.22288939])

In [16]:
y_exact=((2*math.pi**2+3)*np.exp(t)+math.pi*np.sin(math.pi*t)-np.cos(math.pi*t))/(math.pi**2+1)
y_exact

array([ 2.        ,  2.65062979,  3.36734688,  4.11518096,  4.9001451 ,
        5.77864435,  6.85022788,  8.23702688, 10.05843316, 12.41154628,
       15.36590324])

the error compare between Midpoint method and exact solution

In [17]:
[abs(W[i]-y_exact[i]) for i in np.arange(N+1)]

[0.0,
 0.00041848254891663217,
 0.0003516996261065941,
 0.0012664954715075893,
 0.004906844757655904,
 0.012845329252274773,
 0.026164375978643406,
 0.04540679339744891,
 0.07083699600053706,
 0.10294156769753826,
 0.14301385028357494]

# Runge-Kutta method

In [18]:
h=0.2
N=10
W=np.zeros(N+1)
W[0]=2
t=np.linspace(0,2,int(N)+1)
for i in np.arange(1,int(N)+1):
    k1=h*f_2a( t[i-1],W[i-1] )
    k2=h*f_2a( t[i-1]+h/2,W[i-1]+(1/2)*k1 )
    k3=h*f_2a( t[i-1]+h/2,W[i-1]+(1/2)*k2 )
    k4=h*f_2a( t[i],W[i-1]+k3)
    W[i]=W[i-1] +  (1/6)*( k1+2*k2+2*k3+k4 )
W

array([ 2.        ,  2.65062289,  3.36732569,  4.11513832,  4.90007506,
        5.77854206,  6.85008838,  8.23684306, 10.05819338, 12.41123229,
       15.36548873])

In [19]:
y_exact=((2*math.pi**2+3)*np.exp(t)+math.pi*np.sin(math.pi*t)-np.cos(math.pi*t))/(math.pi**2+1)
y_exact

array([ 2.        ,  2.65062979,  3.36734688,  4.11518096,  4.9001451 ,
        5.77864435,  6.85022788,  8.23702688, 10.05843316, 12.41154628,
       15.36590324])

the error compare Runge-Kutta method and exact solution

In [20]:
[abs(W[i]-y_exact[i]) for i in np.arange(N+1)]

[0.0,
 6.892594629714921e-06,
 2.119228957608854e-05,
 4.263468734233555e-05,
 7.003649384529353e-05,
 0.00010229391302729596,
 0.000139503937769625,
 0.00018382132229000092,
 0.00023977565968813508,
 0.0003139926019315453,
 0.0004145076421746552]

# Extrapolation Algorithm

Extrapolation method is one of technique for approximation of definite intergral. This technique invole midpoint method and euler's method. we apply euler's method to find w1, then we can determined w2 by midpoint with w0 and w1. And we reply the similar step to approximation the ending at value t. Extrapolation method is used for accelerating scalar or vector squences.

In [9]:
def extrapolate(f,a,b,y0,TOL,hmax,hmin):
    NK=[2,4,6,8,12,16,24,32]
    N=len(NK)
    Y=np.zeros(N)
    Q=np.zeros((N,N))
    TO=a
    WO=y0
    h=hmax
    FLAG=1
    for i in np.arange(N-1):
        for j in np.arange(i):
            Q[i,j]=( NK[i+1]/NK[j] )**2
    while FLAG==1:
        k=0
        NFLAG=0
        while (k<=N-1) and (NFLAG==0):
            HK=h/NK[k]
            T=TO
            W2=WO
            W3=W2+HK*f(T,W2)
            T=TO+HK
            for j in np.arange( NK[k]-1 ):
                W1=W2
                W2=W3
                W3=W1+2*HK*f(T,W2)
                T=TO+(j+1)*HK
            Y[k]=(W3+W2+HK*f(T,W3))/2
            
            if k>=1:
                j=k
                v=Y[0]
            
                while j>=1:
                    Y[j-1]=Y[j]+( Y[j]-Y[j-1] )/( Q[k-1,j-1]-1 )
                    j=j-1
                
                if abs(Y[0]-v)<=TOL:
                    NFLAG=1
            k=k+1
        k=k-1
        if NFLAG==0:
            h=h/2
            if h<hmin:
                print('min exceeded')
                FLAG=0
        else:
            WO=Y[0]
            TO=TO+h
            print(TO,WO,h)
            if TO>=b:
                FLAG=0
            elif TO+h>b:
                h=b-TO
            elif (k<=2) and (h<0.5*hmax):
                h=2*h      

In [12]:
def f_6(t,v):
    m=10
    g=9.8
    k=0.5
    y=0
    f=-g-k/m*np.sqrt(abs(v))
    return f

In [13]:
a=0
b=5
y0=0
TOL=1e-4
hmin=0.05
hmax=0.25
extrapolate(f_6,a,b,y0,TOL,hmax,hmin)

0.25 -2.4618226723196095 0.25
0.5 -4.9356852417663735 0.25
0.75 -7.416668826704473 0.25
1.0 -9.903404643569619 0.25
1.25 -12.395108977711857 0.25
1.5 -14.89125471824358 0.25
1.75 -17.391455480834235 0.25
2.0 -19.895412144215662 0.25
2.25 -22.402884178878708 0.25
2.5 -24.91367267160583 0.25
2.75 -27.427609537068406 0.25
3.0 -29.94455028482495 0.25
3.25 -32.46436896233801 0.25
3.5 -34.98695449773224 0.25
3.75 -37.51220798004591 0.25
4.0 -40.040040588748454 0.25
4.25 -42.5703719857798 0.25
4.5 -45.10312904512663 0.25
4.75 -47.638244833922855 0.25
5.0 -50.175657784433064 0.25


the first numbers of row are time, and they are 0.25,0.5,0.75.....to 5.0, and the second number of row are estimate solution realte with the times.